"""migrating authors,companies,books

Revision ID: d79179f36490
Revises: 
Create Date: 2025-03-07 14:41:27.089073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79179f36490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('lname', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=85), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('biography', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('author_id'),
    sa.UniqueConstraint('author_id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('location', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('author_id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('books',
    sa.Column('book_ID', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_unit', sa.String(length=30), nullable=False),
    sa.Column('publisher', sa.String(length=12), nullable=True),
    sa.Column('isbn', sa.String(length=30), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=230), nullable=False),
    sa.Column('image', sa.String(length=130), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('book_ID'),
    sa.UniqueConstraint('author_id'),
    sa.UniqueConstraint('book_ID'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('companies')
    op.drop_table('authors')
    # ### end Alembic commands ###
